import pandas as pd
import os
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt

# Assuming df is your DataFrame with the provided data
df = pd.read_csv('cleaned_database.csv')
output_dir = 'img/graphs'
# Create a boxplot for visualization
plt.figure(figsize=(10, 6))
df.boxplot(column='PTS_home', by='SEASON', grid=False)
plt.xlabel('Season')
plt.ylabel('Points Scored at Home')
plt.title('Boxplot of Points Scored at Home Across Seasons')
plt.suptitle('')  # Remove the default title generated by pandas boxplot
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, 'ANOVA'))
plt.show()

# Perform ANOVA
formula = 'PTS_home ~ C(SEASON)'
model = ols(formula, data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print ANOVA results
print(anova_table)

'''
sum_sq       df           F  PR(>F)
C(SEASON)  6.361652e+05     17.0  252.621343     0.0
Residual   3.538298e+06  23886.0         NaN     NaN

Hay una diferencia significativa entre la media de puntos anotada por el equipo de casa entre todas las diferentes temporadas

'''