import pandas as pd

df = pd.read_csv('cleaned_database.csv')

promedio_puntos_casa = df['PTS_home'].mean()
promedio_puntos_visita = df['PTS_away'].mean()
conteo_de_partdos = df['GAME_ID'].count()
moda_puntos_casa = df['PTS_home'].mode()
moda_puntos_visita = df['PTS_away'].mode()
max_porcentaje_tiros_casa = df['FG_PCT_home'].max()
min_porcentaje_tiros_casa = df['FG_PCT_home'].min()
max_porcentaje_tiros_vis = df['FG_PCT_away'].max()
min_porcentaje_tiros_vis = df['FG_PCT_away'].min()
sumatoria_rebotes = df['REB_home'].sum() + df['REB_away'].sum()
var_asistencias_casa = df['AST_home'].var()
desv_est_asistencias_casa = df['AST_home'].std()
asim_puntos_casa = df['PTS_home'].skew()
kurtosis_puntos_casa = df['PTS_home'].kurtosis()

print("Promedio puntos en casa: %.2f Promedio puntos de visita: %.2f" % (promedio_puntos_casa, promedio_puntos_visita))
print("Número de partidos del DB: ", conteo_de_partdos)
print("Moda puntos en casa: %.2f Moda puntos de visita: %.2f" % (moda_puntos_casa, moda_puntos_visita))
print("Máximo porcentaje tiros de un equipo jugando en casa: %.2f Mínimo porcentaje tiros de un equipo jugando en casa: %.2f" % (max_porcentaje_tiros_casa * 100, min_porcentaje_tiros_casa * 100) )
print("Máximo porcentaje tiros de un equipo jugando de visita: %.2f Mínimo porcentaje tiros de un equipo jugando de visita: %.2f" % (max_porcentaje_tiros_vis * 100, min_porcentaje_tiros_vis * 100) )
print("Sumatoria de rebotes: ", sumatoria_rebotes)
print("Varianza asistencias en casa: %.4f" % var_asistencias_casa)
print("Desviación estándar asistencias en casa: %.4f" % desv_est_asistencias_casa)
print("Asimetría puntos en casa: %.4f" % asim_puntos_casa)
print("Kurtosis puntos en casa: %.4f" % kurtosis_puntos_casa)
